### ISSUE TITLE
Cant't use it with nodejs

### ISSUE THREAD

**Issue by LauncherM** [scttcper/irc#4]
I'm trying to use it with nodejs 14.16 but it can't import your module because of the following:
"Error [ERR_MODULE_NOT_FOUND]: Cannot find module './node_modules/@ctrl/irc/dist/src/irc' imported from ./node_modules/@ctrl/irc/dist/src/index.js"

You probably should to add file extension to your import/export lines. 
Example (index.js file):
export { IrcClient } from './irc.js'; //<-- .js added

**Comment by scttcper** [comment]
with node 14 you might want to stay on https://github.com/scttcper/irc/releases/tag/v1.1.4 but i'm not sure. hopefully fixed
